[changelog]
header = ""
body = """
{% if version %}\
    ## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## 未发布
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "🚀 新功能" },
    { message = "^fix", group = "🐛 Bug 修复" },
    { message = "^perf", group = "⚡ 性能优化" },
    { message = "^refactor", group = "🔨 代码重构" },
    { message = "^docs", group = "📝 文档" },
    { message = "^chore", group = "🔧 其他" },
    { message = ".*", group = "🔧 其他" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
